name: Test-Plugin
version: '1.0-SNAPSHOT'
main: com.notkatsu.test.Test_Plugin
api-version: 1.19
authors: [NotKatsu]
description: This is my very first plugin!
website: https://katsu.bio/
commands:
  freeze:
    description: Freeze a player so they can't move anywhere.
